// Create a separate familyData object to hold family information
const familyData = {
  "te-waza": {
    title: "TE-WAZA (Hand Techniques)",
    description:
      "Hand techniques in judo focus on using grip and arm strength to throw opponents.",
  },
  "koshi-waza": {
    title: "KOSHI-WAZA (Hip Techniques)",
    description:
      "Hip techniques involve using your hip as a fulcrum to throw your opponent.",
  },
  "ashi-waza": {
    title: "ASHI-WAZA (Foot Techniques)",
    description:
      "Foot techniques use the legs to sweep, hook, or block opponent's legs to execute throws.",
  },
  "masutemi-waza": {
    title: "MASUTEMI-WAZA (Back Sacrifice Techniques)",
    description:
      "Sacrifice techniques where the thrower falls directly onto their back to throw the opponent.",
  },
  "yoko-sutemi-waza": {
    title: "YOKO-SUTEMI-WAZA (Side Sacrifice Techniques)",
    description:
      "Sacrifice techniques where the thrower falls onto their side to throw the opponent.",
  },
  "osaekomi-waza": {
    title: "OSAEKOMI-WAZA (Holding Techniques)",
    description:
      "Pinning or holding techniques used to immobilize the opponent on their back.",
  },
  "shime-waza": {
    title: "SHIME-WAZA (Choking Techniques)",
    description:
      "Strangling and choking techniques that restrict blood flow or breathing.",
  },
  "kansetsu-waza": {
    title: "KANSETSU-WAZA (Joint Locking Techniques)",
    description:
      "Joint manipulation techniques that apply pressure to an opponent's joints.",
  },
};

// Flattened techniques data - now a simple array with family as a property
const techniqueData = [
  // Te-waza techniques
  {
    name: "Seoi-nage",
    videoId: "zIq0xI0ogxk",
    description: "Shoulder throw",
    levels: ["shodan"],
    family: "te-waza",
  },
  {
    name: "Ippon-seoi-nage",
    videoId: "FQnOlCxo4oI",
    description: "One-arm shoulder throw",
    levels: ["shodan"],
    family: "te-waza",
  },
  {
    name: "Tai-otoshi",
    videoId: "4x6S3Q-Ktv8",
    description: "Body drop",
    levels: ["shodan"],
    family: "te-waza",
  },
  {
    name: "Kata-guruma",
    videoId: "cnHRhSy8yi4",
    description: "Shoulder wheel",
    levels: ["shodan"],
    family: "te-waza",
  },
  {
    name: "Sukui-nage",
    videoId: "vU6aJ2kFxoI",
    description: "Scooping throw",
    levels: ["shodan"],
    family: "te-waza",
  },
  {
    name: "Uki-otoshi",
    videoId: "6H5tmncOY4Q",
    description: "Floating drop",
    levels: ["shodan"],
    family: "te-waza",
  },
  {
    name: "Sumi-otoshi",
    videoId: "lLU9wv52ni0",
    description: "Corner drop",
    levels: ["shodan"],
    family: "te-waza",
  },
  {
    name: "Ko-uchi-gaeshi",
    videoId: "_MWAdYi_LC4",
    description: "Small inner reaping counter",
    levels: ["nidan"],
    family: "te-waza",
  },
  {
    name: "Seoi-otoshi",
    videoId: "vu1TMVNnq34",
    description: "Shoulder drop",
    levels: ["sandan"],
    family: "te-waza",
  },
  {
    name: "Obi-otoshi",
    videoId: "ff8U2TVZIYI",
    description: "Belt drop",
    levels: ["sandan"],
    family: "te-waza",
  },
  {
    name: "Yama-arashi",
    videoId: "MGlyKmSuzdc",
    description: "Mountain storm",
    levels: ["sandan"],
    family: "te-waza",
  },
  {
    name: "Obi-tori-gaeshi",
    videoId: "bpc82SrunUU",
    description: "Belt grab reversal",
    levels: ["sandan"],
    family: "te-waza",
  },
  {
    name: "Morote-gari",
    videoId: "BHLQS4K85bs",
    description: "Two-handed reap",
    levels: ["sandan"],
    family: "te-waza",
  },
  {
    name: "Kuchiki-taoshi",
    videoId: "ZNL47q1aJNY",
    description: "Single leg takedown",
    levels: ["sandan"],
    family: "te-waza",
  },
  {
    name: "Kibisu-gaeshi",
    videoId: "tJylJYfBliA",
    description: "Heel trip",
    levels: ["sandan"],
    family: "te-waza",
  },
  {
    name: "Uchi-mata-sukashi",
    videoId: "V-RS3uhtVWM",
    description: "Inner thigh throw slip",
    levels: ["sandan"],
    family: "te-waza",
  },
  // Koshi-waza techniques
  {
    name: "Uki-goshi",
    videoId: "bPKwtB4lyOQ",
    description: "Floating hip throw",
    levels: ["shodan"],
    family: "koshi-waza",
  },
  {
    name: "O-goshi",
    videoId: "yhu1mfy2vJ4",
    description: "Major hip throw",
    levels: ["shodan"],
    family: "koshi-waza",
  },
  {
    name: "Koshi-guruma",
    videoId: "SU7Id6uVJ44",
    description: "Hip wheel",
    levels: ["shodan"],
    family: "koshi-waza",
  },
  {
    name: "Tsurikomi-goshi",
    videoId: "McfzA0yRVt4",
    description: "Lifting pulling hip throw",
    levels: ["shodan"],
    family: "koshi-waza",
  },
  {
    name: "Harai-goshi",
    videoId: "qTo8HlAAkOo",
    description: "Sweeping hip throw",
    levels: ["shodan"],
    family: "koshi-waza",
  },
  {
    name: "Tsuri-goshi",
    videoId: "51Htlp7xEvE",
    description: "Lifting hip throw",
    levels: ["shodan"],
    family: "koshi-waza",
  },
  {
    name: "Hane-goshi",
    videoId: "M9_7De6A1kk",
    description: "Spring hip throw",
    levels: ["shodan"],
    family: "koshi-waza",
  },
  {
    name: "Utsuri-goshi",
    videoId: "4pQd_bEnlf0",
    description: "Changing hip throw",
    levels: ["shodan"],
    family: "koshi-waza",
  },
  {
    name: "Ushiro-goshi",
    videoId: "ORIYstuxYT8",
    description: "Rear hip throw",
    levels: ["shodan"],
    family: "koshi-waza",
  },
  {
    name: "Sode-tsurikomi-goshi",
    videoId: "QsmAxpmYLOI",
    description: "Sleeve lifting pulling hip throw",
    levels: ["sandan"],
    family: "koshi-waza",
  },
  // Ashi-waza techniques
  {
    name: "De-ashi-harai",
    videoId: "4BUUvqxi_Kk",
    description: "Advanced foot sweep",
    levels: ["shodan"],
    family: "ashi-waza",
  },
  {
    name: "Hiza-guruma",
    videoId: "JPJx9-oAVns",
    description: "Knee wheel",
    levels: ["shodan"],
    family: "ashi-waza",
  },
  {
    name: "Sasae-tsurikomi-ashi",
    videoId: "699i--pvYmE",
    description: "Supporting foot lift-pull throw",
    levels: ["shodan"],
    family: "ashi-waza",
  },
  {
    name: "O-soto-gari",
    videoId: "c-A_nP7mKAc",
    description: "Major outer reap",
    levels: ["shodan"],
    family: "ashi-waza",
  },
  {
    name: "O-uchi-gari",
    videoId: "0itJFhV9pDQ",
    description: "Major inner reap",
    levels: ["shodan"],
    family: "ashi-waza",
  },
  {
    name: "Ko-soto-gari",
    videoId: "jeQ541ScLB4",
    description: "Minor outer reap",
    levels: ["shodan"],
    family: "ashi-waza",
  },
  {
    name: "Ko-uchi-gari",
    videoId: "3Jb3tZvr9Ng",
    description: "Minor inner reap",
    levels: ["shodan"],
    family: "ashi-waza",
  },
  {
    name: "Okuri-ashi-harai",
    videoId: "nw1ZdRjrdRI",
    description: "Sliding foot sweep",
    levels: ["shodan"],
    family: "ashi-waza",
  },
  {
    name: "Uchi-mata",
    videoId: "iUpSu5J-bgw",
    description: "Inner thigh throw",
    levels: ["shodan"],
    family: "ashi-waza",
  },
  {
    name: "Ko-soto-gake",
    videoId: "8b6kY4s4zH4",
    description: "Minor outer hook",
    levels: ["shodan"],
    family: "ashi-waza",
  },
  {
    name: "Ashi-guruma",
    videoId: "ROeayhvom9U",
    description: "Leg wheel",
    levels: ["shodan"],
    family: "ashi-waza",
  },
  {
    name: "Harai-tsurikomi-ashi",
    videoId: "gGPXvWL8VbE",
    description: "Lift-pull foot sweep",
    levels: ["shodan"],
    family: "ashi-waza",
  },
  {
    name: "O-guruma",
    videoId: "SnZciTAY9vc",
    description: "Major wheel",
    levels: ["shodan"],
    family: "ashi-waza",
  },
  {
    name: "O-soto-guruma",
    videoId: "92KbCm6pQeI",
    description: "Major outer wheel",
    levels: ["shodan"],
    family: "ashi-waza",
  },
  {
    name: "O-soto-gaeshi",
    videoId: "8ZjM3X_EANo",
    description: "Major outer reap counter",
    levels: ["nidan"],
    family: "ashi-waza",
  },
  {
    name: "O-uchi-gaeshi",
    videoId: "dCyZTXyjIXE",
    description: "Major inner reap counter",
    levels: ["nidan"],
    family: "ashi-waza",
  },
  {
    name: "Hane-goshi-gaeshi",
    videoId: "9bZAZSBtnGs",
    description: "Spring hip counter",
    levels: ["nidan"],
    family: "ashi-waza",
  },
  {
    name: "Harai-goshi-gaeshi",
    videoId: "4U3It-7PPsc",
    description: "Sweeping hip counter",
    levels: ["nidan"],
    family: "ashi-waza",
  },
  {
    name: "Uchi-mata-gaeshi",
    videoId: "Sy6sLWxkWYw",
    description: "Inner thigh counter",
    levels: ["nidan"],
    family: "ashi-waza",
  },
  {
    name: "O-soto-otoshi",
    videoId: "2DsVvDw7b8g",
    description: "Major outer drop",
    levels: ["sandan"],
    family: "ashi-waza",
  },
  {
    name: "Tsubame-gaeshi",
    videoId: "GwweWqqFB5g",
    description: "Swallow counter",
    levels: ["sandan"],
    family: "ashi-waza",
  },
  // Masutemi-waza techniques
  {
    name: "Tomoe-nage",
    videoId: "880WbHvHv6A",
    description: "Circle throw",
    levels: ["shodan"],
    family: "masutemi-waza",
  },
  {
    name: "Sumi-gaeshi",
    videoId: "5VhduA5xkbA",
    description: "Corner reversal",
    levels: ["shodan"],
    family: "masutemi-waza",
  },
  {
    name: "Ura-nage",
    videoId: "Fgi9b8DJ5sQ",
    description: "Rear throw",
    levels: ["shodan"],
    family: "masutemi-waza",
  },
  {
    name: "Hikikomi-gaeshi",
    videoId: "92zUYWBp5N8",
    description: "Pulling down sacrifice",
    levels: ["sandan"],
    family: "masutemi-waza",
  },
  {
    name: "Tawara-gaeshi",
    videoId: "TmTWgrmViZc",
    description: "Rice bag throw",
    levels: ["sandan"],
    family: "masutemi-waza",
  },
  // Yoko-sutemi-waza techniques
  {
    name: "Yoko-otoshi",
    videoId: "MnNG67pF_a0",
    description: "Side drop",
    levels: ["shodan"],
    family: "yoko-sutemi-waza",
  },
  {
    name: "Tani-otoshi",
    videoId: "3b9Me3Fohpk",
    description: "Valley drop",
    levels: ["shodan"],
    family: "yoko-sutemi-waza",
  },
  {
    name: "Hane-makikomi",
    videoId: "6CRBGLGz9j8",
    description: "Spring wrap-around throw",
    levels: ["shodan"],
    family: "yoko-sutemi-waza",
  },
  {
    name: "Soto-makikomi",
    videoId: "bWG9O1BVKtQ",
    description: "Outer wrap-around throw",
    levels: ["shodan"],
    family: "yoko-sutemi-waza",
  },
  {
    name: "Uki-waza",
    videoId: "weVOpJ63gII",
    description: "Floating technique",
    levels: ["shodan"],
    family: "yoko-sutemi-waza",
  },
  {
    name: "Yoko-wakare",
    videoId: "bp1tscHlePI",
    description: "Side separation",
    levels: ["shodan"],
    family: "yoko-sutemi-waza",
  },
  {
    name: "Yoko-guruma",
    videoId: "MehP6I5cY2c",
    description: "Side wheel",
    levels: ["shodan"],
    family: "yoko-sutemi-waza",
  },
  {
    name: "Yoko-gake",
    videoId: "tP1Sj1uDfSo",
    description: "Side hook",
    levels: ["shodan"],
    family: "yoko-sutemi-waza",
  },
  {
    name: "Uchi-makikomi",
    videoId: "5BowcjduxVc",
    description: "Inner wrap-around throw",
    levels: ["sandan"],
    family: "yoko-sutemi-waza",
  },
  {
    name: "Daki-wakare",
    videoId: "Hr0cOMGBDYo",
    description: "High separation",
    levels: ["sandan"],
    family: "yoko-sutemi-waza",
  },
  {
    name: "O-soto-makikomi",
    videoId: "DGDv2oMwmas",
    description: "Major outer wrap-around throw",
    levels: ["sandan"],
    family: "yoko-sutemi-waza",
  },
  {
    name: "Uchi-mata-makikomi",
    videoId: "jZXENTLpJCI",
    description: "Inner thigh wrap-around throw",
    levels: ["sandan"],
    family: "yoko-sutemi-waza",
  },
  {
    name: "Harai-makikomi",
    videoId: "VBaHzKaCXss",
    description: "Sweeping wrap-around throw",
    levels: ["sandan"],
    family: "yoko-sutemi-waza",
  },
  {
    name: "Ko-uchi-makikomi",
    videoId: "_1eygIXLD_w",
    description: "Small inner wrap-around throw",
    levels: ["sandan"],
    family: "yoko-sutemi-waza",
  },
  {
    name: "Kani-basami",
    videoId: "OR-HGHnarYc",
    description: "Crab scissors",
    levels: ["sandan"],
    family: "yoko-sutemi-waza",
  },
  {
    name: "Kawazu-gake",
    videoId: "w6G57bWACi0",
    description: "Frog hook",
    levels: ["sandan"],
    family: "yoko-sutemi-waza",
  },
  // Osaekomi-waza techniques
  {
    name: "Kesa-gatame",
    videoId: "NDaQuJOFBYk",
    description: "Scarf hold",
    levels: ["shodan"],
    family: "osaekomi-waza",
  },
  {
    name: "Kata-gatame",
    videoId: "zQR3IOXxO_Q",
    description: "Shoulder hold",
    levels: ["shodan"],
    family: "osaekomi-waza",
  },
  {
    name: "Kuzure-kami-shiho-gatame",
    videoId: "YUrogQWdwiY",
    description: "Modified upper four-corner hold",
    levels: ["shodan"],
    family: "osaekomi-waza",
  },
  {
    name: "Yoko-shiho-gatame",
    videoId: "TT7XJVSEQxA",
    description: "Side four-corner hold",
    levels: ["shodan"],
    family: "osaekomi-waza",
  },
  {
    name: "Tate-shiho-gatame",
    videoId: "55-rFmBx53g",
    description: "Vertical four-corner hold",
    levels: ["shodan"],
    family: "osaekomi-waza",
  },
  {
    name: "Kuzure-kesa-gatame",
    videoId: "Q2fb9jaoUFQ",
    description: "Modified scarf hold",
    levels: ["shodan"],
    family: "osaekomi-waza",
  },
  {
    name: "Kami-shiho-gatame",
    videoId: "HFuMjOv0WN8",
    description: "Upper four-corner hold",
    levels: ["shodan"],
    family: "osaekomi-waza",
  },
  {
    name: "Ushiro-kesa-gatame",
    videoId: "SBapox2M2dE",
    description: "Rear scarf hold",
    levels: ["nidan"],
    family: "osaekomi-waza",
  },
  {
    name: "Uki-gatame",
    videoId: "e_lAjik1SUM",
    description: "Floating hold",
    levels: ["sandan"],
    family: "osaekomi-waza",
  },
  {
    name: "Ura-gatame",
    videoId: "eeAHZB0v3XY",
    description: "Back hold",
    levels: ["sandan"],
    family: "osaekomi-waza",
  },
  // Shime-waza techniques
  {
    name: "Nami-juji-jime",
    videoId: "k2cHry9HByQ",
    description: "Normal cross strangle",
    levels: ["shodan"],
    family: "shime-waza",
  },
  {
    name: "Gyaku-juji-jime",
    videoId: "t3tQriIPdlI",
    description: "Reverse cross strangle",
    levels: ["shodan"],
    family: "shime-waza",
  },
  {
    name: "Kata-juji-jime",
    videoId: "3VZVUAmiMD8",
    description: "Half cross strangle",
    levels: ["shodan"],
    family: "shime-waza",
  },
  {
    name: "Hadaka-jime",
    videoId: "9f0n8jez7iA",
    description: "Naked strangle",
    levels: ["shodan"],
    family: "shime-waza",
  },
  {
    name: "Okuri-eri-jime",
    videoId: "EiqyoVcIAi8",
    description: "Sliding collar strangle",
    levels: ["shodan"],
    family: "shime-waza",
  },
  {
    name: "Kata-ha-jime",
    videoId: "yaTGgRjnwB8",
    description: "Single-wing strangle",
    levels: ["shodan"],
    family: "shime-waza",
  },
  {
    name: "Sankaku-jime",
    videoId: "lq1CUBRAm7s",
    description: "Triangle strangle",
    levels: ["nidan"],
    family: "shime-waza",
  },
  {
    name: "Kata-te-jime",
    videoId: "cHeIs-fSqwE",
    description: "One-hand strangle",
    levels: ["sandan"],
    family: "shime-waza",
  },
  {
    name: "Ryote-jime",
    videoId: "-RHC4V7TQiY",
    description: "Two-hand strangle",
    levels: ["sandan"],
    family: "shime-waza",
  },
  {
    name: "Sode-guruma-jime",
    videoId: "E3nvQzClcAU",
    description: "Sleeve wheel strangle",
    levels: ["sandan"],
    family: "shime-waza",
  },
  {
    name: "Tsukkomi-jime",
    videoId: "dKKpnD3eLcY",
    description: "Thrust strangle",
    levels: ["sandan"],
    family: "shime-waza",
  },
  {
    name: "Do-jime",
    videoId: "D_0fFcoIbvY",
    description: "Body scissors",
    levels: ["sandan"],
    family: "shime-waza",
  },
  // Kansetsu-waza techniques
  {
    name: "Ude-garami",
    videoId: "AIlTvZb4RlE",
    description: "Entangled arm lock",
    levels: ["shodan"],
    family: "kansetsu-waza",
  },
  {
    name: "Ude-hishigi-juji-gatame",
    videoId: "OWgSOlCuMXw",
    description: "Cross armlock",
    levels: ["shodan"],
    family: "kansetsu-waza",
  },
  {
    name: "Ude-hishigi-ude-gatame",
    videoId: "SBf0aTma1VI",
    description: "Straight arm lock",
    levels: ["shodan"],
    family: "kansetsu-waza",
  },
  {
    name: "Ude-hishigi-hiza-gatame",
    videoId: "H2HtAJdiJcE",
    description: "Knee armlock",
    levels: ["shodan"],
    family: "kansetsu-waza",
  },
  {
    name: "Ude-hishigi-waki-gatame",
    videoId: "8F5p1zuJRG0",
    description: "Armpit armlock",
    levels: ["shodan"],
    family: "kansetsu-waza",
  },
  {
    name: "Ude-hishigi-hara-gatame",
    videoId: "ZzEycg8R_9M",
    description: "Stomach armlock",
    levels: ["shodan"],
    family: "kansetsu-waza",
  },
  {
    name: "Ude-hishigi-ashi-gatame",
    videoId: "ClY7g_pX-4s",
    description: "Leg armlock",
    levels: ["sandan"],
    family: "kansetsu-waza",
  },
  {
    name: "Ude-hishigi-te-gatame",
    videoId: "6DnvhY0tQVM",
    description: "Hand armlock",
    levels: ["sandan"],
    family: "kansetsu-waza",
  },
  {
    name: "Ude-hishigi-sankaku-gatame",
    videoId: "WefAmW4azhk",
    description: "Triangular armlock",
    levels: ["sandan"],
    family: "kansetsu-waza",
  },
  {
    name: "Ashi-garami",
    videoId: "BWWb0GoAtZw",
    description: "Entangled leg lock",
    levels: ["sandan"],
    family: "kansetsu-waza",
  },
];
